DROP TABLE TBL_ACADEMY;
DROP SEQUENCE SEQ_ACADEMY;

CREATE SEQUENCE SEQ_ACADEMY;

CREATE TABLE TBL_ACADEMY (
   ANAME VARCHAR2(200) NOT NULL,
   AID VARCHAR2(200) NOT NULL,
   ACORPORATE VARCHAR2(200) NOT NULL,
   APWD VARCHAR2(200) NOT NULL,
   APWDQ VARCHAR2(1000) NOT NULL,
   APWDA VARCHAR2(1000) NOT NULL,
   AEMAIL VARCHAR2(200) NOT NULL,
   APHONE VARCHAR2(100) NOT NULL,   
   AZIPCODE VARCHAR2(1000) NOT NULL,
   AADDRESS VARCHAR2(1000) NOT NULL,
   AADDRESSDETAIL VARCHAR2(1000) NOT NULL,
   CHECKACADEMY NUMBER(10) DEFAULT 1
);


DROP TABLE TBL_ACADEMY;
ALTER TABLE TBL_ACADEMY ADD CONSTRAINT FK_ACADEMY FOREIGN KEY(AID)
REFERENCES TBL_STUDENT(SID);

ALTER TABLE TBL_ACADEMY ADD CONSTRAINT PK_ACADEMY PRIMARY KEY(AID);

SELECT * FROM TBL_ACADEMY;

INSERT INTO HR.TBL_ACADEMY
(ANAME, AID, ACORPORATE, APWD, APWDQ, APWDA, AEMAIL, APHONE, AZIPCODE, AADDRESS, AADDRESSDETAIL)
VALUES('1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1'
);

CREATE TABLE TBL_ACADEMY_BOARD(
	ANO NUMBER(10),
	ACADEMYAREA VARCHAR2(200) NOT NULL,
	ACADEMYKIND VARCHAR2(200) NOT NULL,
	ACADEMYPHOTO VARCHAR2(200) NOT NULL,
	ACADEMYTITLE VARCHAR2(200) NOT NULL,
	ACADEMYID VARCHAR2(200) NOT NULL,
	ACADEMYCONTENT VARCHAR2(2000) NOT NULL,
	ACADEMYINTRO VARCHAR2(2000) NOT NULL,
	ACADEMYYOUTUBE VARCHAR2(200) NOT NULL
);

ALTER TABLE TBL_ACADEMY_BOARD ADD CONSTRAINT FK_ACADEMY_BOARD FOREIGN KEY (ACADEMYID) REFERENCES TBL_ACADEMY(AID);
ALTER TABLE TBL_ACADEMY_BOARD ADD CONSTRAINT PK_ACADEMY_BOARD PRIMARY KEY(ANO);
SELECT * FROM TBL_ACADEMY_BOARD;

CREATE TABLE TBL_ACADEMY_PHOTO(
	PNO NUMBER(10),
	ACADEMYID VARCHAR2(200) NOT NULL,
	PHOTO VARCHAR2(200) NOT NULL
);

ALTER TABLE TBL_ACADEMY_PHOTO ADD CONSTRAINT FK_ACADEMY_PHOTO FOREIGN KEY (ACADEMYID) REFERENCES TBL_ACADEMY(AID);
ALTER TABLE TBL_ACADEMY_PHOTO ADD CONSTRAINT PK_ACADEMY_PHOTO PRIMARY KEY(PNO);
SELECT * FROM TBL_ACADEMY_PHOTO;

CREATE TABLE TBL_ACADEMY_TEACHER(
	TNO NUMBER(10),
	ACADEMYID VARCHAR2(200) NOT NULL,
	TEACHERNAME VARCHAR2(200) NOT NULL,
	TEACHERPHOTO VARCHAR2(200) NOT NULL,
	TEACHERINTRO VARCHAR2(200) NOT NULL,
	TEACHERCAREER VARCHAR2(200) NOT NULL,
	TEACHERSUBJECT VARCHAR2(200) NOT NULL
);

ALTER TABLE TBL_ACADEMY_TEACHER ADD CONSTRAINT FK_ACADEMY_TEACHER FOREIGN KEY (ACADEMYID) REFERENCES TBL_ACADEMY(AID);
ALTER TABLE TBL_ACADEMY_TEACHER ADD CONSTRAINT PK_ACADEMY_TEACHER PRIMARY KEY(TNO);
SELECT * FROM TBL_ACADEMY_TEACHER;