DROP TABLE TBL_ACADEMY;
DROP SEQUENCE SEQ_ACADEMY;

CREATE SEQUENCE SEQ_ACADEMY;

CREATE TABLE TBL_ACADEMY (
   ANAME VARCHAR2(200) NOT NULL,
   AID VARCHAR2(200) NOT NULL PRIMARY KEY,
   ACORPORATE VARCHAR2(200) NOT NULL,
   APWD VARCHAR2(200) NOT NULL,
   APWDQ VARCHAR2(1000) NOT NULL,
   APWDA VARCHAR2(1000) NOT NULL,
   AEMAIL VARCHAR2(200) NOT NULL,
   APHONE VARCHAR2(100) NOT NULL,   
   AZIPCODE VARCHAR2(1000) NOT NULL,
   AADDRESS VARCHAR2(1000) NOT NULL,
   AADDRESSDETAIL VARCHAR2(1000) NOT NULL,
   CHECKACADEMY NUMBER(10) DEFAULT 1
);
DROP TABLE TBL_ACADEMY;
ALTER TABLE TBL_ACADEMY ADD CONSTRAINT FK_ACADEMY FOREIGN KEY(AID)
REFERENCES TBL_STUDENT(SID);

ALTER TABLE TBL_ACADEMY ADD CONSTRAINT PK_ACADEMY PRIMARY KEY(AID);

SELECT * FROM TBL_ACADEMY;

INSERT INTO HR.TBL_ACADEMY
(ANAME, AID, ACORPORATE, APWD, APWDQ, APWDA, AEMAIL, APHONE, AZIPCODE, AADDRESS, AADDRESSDETAIL)
VALUES('1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1'
);

