DROP TABLE TBL_ACADEMY;
DROP SEQUENCE SEQ_ACADEMY;

CREATE SEQUENCE SEQ_ACADEMY;

CREATE TABLE TBL_ACADEMY (
   ANAME VARCHAR2(200) NOT NULL,
   AID VARCHAR2(200) NOT NULL,
   ACORPORATE VARCHAR2(200) NOT NULL,
   APWD VARCHAR2(200) NOT NULL,
   APWDQ VARCHAR2(1000) NOT NULL,
   APWDA VARCHAR2(1000) NOT NULL,
   AEMAIL VARCHAR2(200) NOT NULL,
   APHONE VARCHAR2(100) NOT NULL,   
   AZIPCODE VARCHAR2(1000) NOT NULL,
   AADDRESS VARCHAR2(1000) NOT NULL,
   AADDRESSDETAIL VARCHAR2(1000) NOT NULL,
   CHECKACADEMY NUMBER(10) DEFAULT 1
);

ALTER TABLE TBL_ACADEMY ADD CONSTRAINT PK_ACADEMY PRIMARY KEY(AID);

SELECT * FROM TBL_ACADEMY;

/*DROP TABLE TBL_STUDENT ;*/
ALTER TABLE TBL_ACADEMY ADD CONSTRAINT PK_ACADEMY PRIMARY KEY(A_ID);
DROP TABLE TBL_ACADEMY;
SELECT * FROM TBL_ACADEMY;

SELECT * FROM TBL_ACADEMY;