--시퀀스를 생성할 때에는 'SEQ_'로 시작하는 것이 일반적이다
CREATE SEQUENCE SEQ_STUDENT;

--테이블 생성시 'TBL_'또는 'T_'와 같이 시작하는 것이 일반적이다.
CREATE TABLE TBL_STUDENT(
	BNO NUMBER(10),
	S_ID VARCHAR2(20) NOT NULL,
	S_PWD VARCHAR2(20) NOT NULL,
	S_PWD_Q VARCHAR(100) NOT NULL,
	S_PWD_A VARCHAR(100) NOT NULL,
	S_LAST_NAME VARCHAR2(10) NOT NULL,
	S_FIRST_NAME VARCHAR2(10) NOT NULL,
	S_GENDER VARCHAR(5) NOT NULL,
	S_EMAIL VARCHAR(20) NOT NULL,
	S_PHONE VARCHAR(10) NOT NULL,	
	S_RESIDENCE VARCHAR(100) NOT NULL
);

ALTER TABLE TBL_STUDENT ADD CONSTRAINT PK_STUDENT PRIMARY KEY(BNO);

SELECT * FROM TBL_STUDENT;