CREATE TABLE TBL_CUSTOMER(
   BNO NUMBER PRIMARY KEY,
   RN NUMBER,
   TITLE VARCHAR(200),
   CONTENT VARCHAR(2000),
   WRITER VARCHAR(100),
   REGDATE DATE DEFAULT SYSDATE,
   PASSWORD VARCHAR(200),
   REACT VARCHAR(100)
);
SELECT * FROM TBL_CUSTOMER;
DROP  TABLE TBL_CUSTOMER;
/*DROP TABE TBL_CUSTOMER;*/
/*시퀀스 삭제*/
/*DROP SEQUENCE SEQ_CUSTOMER;*/
CREATE SEQUENCE SEQ_CUSTOMER;