CREATE TABLE TBL_REVIEW (
	BNO NUMBER(10),
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(3000) NOT NULL,
	WRITER VARCHAR2(200) NOT NULL,
	REGDATE DATE DEFAULT SYSDATE,
	UPDATEDATE DATE DEFAULT SYSDATE
);
ALTER TABLE TBL_REVIEW ADD CONSTRAINT PK_REVIEW PRIMARY KEY(BNO);
SELECT * FROM TBL_REVIEW;

DELETE FROM TBL_REVIEW;
SELECT COUNT(*) FROM TBL_REVIEW;

	SELECT /*+ INDEX_DESC(TBL_REVIEW PK_REVIEW) */ ROWNUM RN, BNO, TITLE, CONTENT, WRITER , REGDATE , UPDATEDATE  FROM TBL_REVIEW;
		
CREATE SEQUENCE SEQ_REVIEW;

DROP TABLE TBL_REVIEW;

INSERT INTO TBL_REVIEW(BNO, TITLE, CONTENT, WRITER) 
(SELECT SEQ_REVIEW.NEXTVAL, TITLE, CONTENT, WRITER FROM TBL_REVIEW);



INSERT INTO TBL_REVIEW (BNO, TITLE, CONTENT, WRITER)(SELECT SEQ_REVIEW.NEXTVAL, TITLE, CONTENT, WRITER FROM TBL_REVIEW);
--테이블 생성 시 넣는 의미 없는 데이터를 토이 데이터(toy data)혹은 더미 데이터(dummy data)라고 한다.
INSERT INTO TBL_REVIEW(BNO, TITLE, CONTENT, WRITER) 
VALUES(SEQ_REVIEW.NEXTVAL, '테스트 제목1', '테스트 내용1', 'TEST');

--더미데티어 추가시에 SQL문 많은 양의 더미 데티어를 생성 할 수 있다.
INSERT INTO TBL_BOARD(BNO, TITLE, CONTENT, WRITER)
(SELECT SEQ_BOARD.NEXTVAL, TITLE, CONTENT, WRITER FROM TBL_BOARD);