CREATE SEQUENCE SEQ_ACADEMY_BOARD;
CREATE TABLE TBL_ACADEMY_BOARD(
   ANO NUMBER(10),
   ACADEMYAREA VARCHAR2(200) ,
   ACADEMYKIND VARCHAR2(200),
   ACADEMYPHOTO VARCHAR2(200),
   ACADEMYTITLE VARCHAR2(200) ,
   ACADEMYID VARCHAR2(200) ,
   ACADEMYNAME VARCHAR2(200) ,
   ACADEMYCONTENT VARCHAR2(2000) ,
   ACADEMYINTRO VARCHAR2(2000) ,
   ACADEMYYOUTUBE VARCHAR2(200) ,
   ACADEMYTAG VARCHAR2(200),
   ACADEMYMAPPHOTO VARCHAR2(200),
   MAPDETAIL VARCHAR2(1000),
   REGDATE DATE DEFAULT SYSDATE
);

DROP TABLE TBL_ACADEMY_BOARD;
ALTER TABLE TBL_ACADEMY_BOARD ADD CONSTRAINT FK_ACADEMY_BOARD FOREIGN KEY (ACADEMYID) REFERENCES TBL_ACADEMY(AID);
ALTER TABLE TBL_ACADEMY_BOARD ADD CONSTRAINT PK_ACADEMY_BOARD PRIMARY KEY(ANO);
SELECT * FROM TBL_ACADEMY_BOARD;
DELETE FROM TBL_ACADEMY_BOARD;

INSERT INTO TBL_ACADEMY_BOARD (ANO, ACADEMYAREA, ACADEMYKIND, ACADEMYPHOTO, ACADEMYTITLE, ACADEMYID, ACADEMYCONTENT, ACADEMYNAME, ACADEMYINTRO, ACADEMYYOUTUBE, ACADEMYTAG) 
(SELECT  SEQ_ACADEMY_BOARD.NEXTVAL,  ACADEMYAREA, ACADEMYKIND, ACADEMYPHOTO, ACADEMYTITLE, ACADEMYID, ACADEMYCONTENT, ACADEMYNAME, ACADEMYINTRO, ACADEMYYOUTUBE, ACADEMYTAG FROM TBL_ACADEMY_BOARD);

SELECT SEQ_ACADEMY_BOARD.NEXTVAL FROM DUAL;
-----------학원강사------------
CREATE SEQUENCE SEQ_TEACHER;
ALTER TABLE TBL_TEACHER ADD CONSTRAINT FK_TEACHER FOREIGN KEY (ANO) REFERENCES TBL_ACADEMY_BOARD(ANO);
DROP TABLE TBL_TEACHER;
SELECT * FROM TBL_TEACHER;
CREATE TABLE TBL_TEACHER(
	ANO NUMBER,
	NAME VARCHAR2(200),
	GENDER VARCHAR2(200),
	PHOTO VARCHAR2(200),
	INTRO VARCHAR2(2000)
);
DROP TABLE TBL_TEACHER;
ALTER TABLE TBL_TEACHER ADD CONSTRAINT FK_TEACHER FOREIGN KEY(ANO) REFERENCES TBL_ACADEMY_BOARD(ANO);
SELECT * FROM TBL_TEACHER;


-------- 학원 시설물 ----------
CREATE TABLE TBL_ACADEMY_PHOTO(
	ANO NUMBER,
	PHOTO VARCHAR2(1000)
);
ALTER TABLE TBL_ACADEMY_PHOTO ADD CONSTRAINT PK_ACADEMY_PHOTO FOREIGN KEY (ANO) REFERENCES TBL_ACADEMY_BOARD(ANO);
DROP TABLE TBL_ACADEMY_PHOTO;
SELECT * FROM TBL_ACADEMY_PHOTO;
DELETE FROM TBL_ACADEMY_PHOTO;

INSERT INTO TBL_ACADEMY_PHOTO VALUES(75,123);