CREATE TABLE TBL_CUSTOMER (
	BNO NUMBER(10),
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(3000) NOT NULL,
	WRITER VARCHAR2(200) NOT NULL,
	REGDATE DATE DEFAULT SYSDATE,
	PASSWORD VARCHAR2(200) NOT NULL,
	REACT VARCHAR2(10)
);
ALTER TABLE TBL_CUSTOMER ADD CONSTRAINT PK_CUSTOMER PRIMARY KEY(BNO);
SELECT * FROM TBL_CUSTOMER;

SELECT COUNT(*) FROM TBL_CUSTOMER;

SELECT /*+ INDEX_DESC(TBL_REVIEW PK_REVIEW) */ ROWNUM RN, BNO, TITLE, CONTENT, WRITER , REGDATE ,REACT  FROM TBL_CUSTOMER;
		
CREATE SEQUENCE SEQ_CUSTOMER;

DROP TABLE TBL_CUSTOMER;

INSERT INTO TBL_CUSTOMER(BNO, TITLE, CONTENT, WRITER, PASSWORD, REACT) 
(SELECT SEQ_CUSTOMER.NEXTVAL, TITLE, CONTENT, WRITER, PASSWORD, REACT FROM TBL_CUSTOMER);


--테이블 생성 시 넣는 의미 없는 데이터를 토이 데이터(toy data)혹은 더미 데이터(dummy data)라고 한다.
INSERT INTO TBL_CUSTOMER(BNO, TITLE, CONTENT, WRITER, PASSWORD,REACT) 
VALUES(SEQ_REVIEW.NEXTVAL, '테스트 제목1', '테스트 내용1', 'TEST','1234','O');

--더미데티어 추가시에 SQL문 많은 양의 더미 데티어를 생성 할 수 있다.
INSERT INTO TBL_CUSTOMER(BNO, TITLE, CONTENT, WRITER)
(SELECT SEQ_BOARD.NEXTVAL, TITLE, CONTENT, WRITER FROM TBL_CUSTOMER);