CREATE SEQUENCE SEQ_STUDENT;

CREATE SEQUENCE SEQ_STUDENT;


CREATE TABLE TBL_STUDENT(
   SID VARCHAR2(200) NOT NULL,
   SPWD VARCHAR2(200) NOT NULL,
   SPWDQ VARCHAR2(200) NOT NULL,
   SPWDA VARCHAR2(200) NOT NULL,
   SLASTNAME VARCHAR2(100) NOT NULL,
   SFIRSTNAME VARCHAR2(100) NOT NULL,
   SEMAIL VARCHAR2(200) NOT NULL,
   SBIRTH VARCHAR2(300) NOT NULL,
   SPHONE VARCHAR2(100) NOT NULL,   
   SZIPCODE VARCHAR2(1000) NOT NULL,
   SADDRESS VARCHAR2(1000) NOT NULL,
   SADDRESSDETAIL VARCHAR2(1000) NOT NULL,
   CHECKACADEMY NUMBER(10) DEFAULT 0
);
DROP TABLE TBL_STUDENT ;
ALTER TABLE TBL_STUDENT ADD CONSTRAINT PK_STUDENT PRIMARY KEY(SID);
SELECT * FROM TBL_STUDENT;

SELECT * FROM TBL_ACADEMY;


INSERT INTO HR.TBL_STUDENT
( SID, SPWD, SPWDQ, SPWDA, SLASTNAME, SFIRSTNAME, SEMAIL, SBIRTH, SPHONE, SZIPCODE, SADDRESS, SADDRESSDETAIL)
VALUES( 'stu', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1'
);

-------------리뷰--------------------
CREATE TABLE TBL_REPLY(
	RNO NUMBER(10),
	BNO NUMBER(10) NOT NULL,
	REPLY VARCHAR2(2000) NOT NULL,
	REPLYER VARCHAR2(100) NOT NULL,
	REPLYDATE DATE DEFAULT SYSDATE,
	UPDATEDATE DATE DEFAULT SYSDATE
);

SELECT * FROM TBL_REPLY;

DROP TABLE TBL_REPLY;

ALTER TABLE TBL_REPLY ADD CONSTRAINT PK_REPLY PRIMARY KEY(RNO);
ALTER TABLE TBL_REPLY ADD CONSTRAINT FK_REPLY_BOARD FOREIGN KEY(BNO) REFERENCES TBL_CUSTOMER(BNO);

CREATE SEQUENCE SEQ_REPLYS;

CREATE SEQUENCE SEQ_RE;
SELECT * FROM USER_SEQUENCES;

INSERT INTO TBL_REPLY(RNO, BNO, REPLY, REPLYER) 
VALUES(SEQ_REPLY.NEXTVAL, '2762', '리뷰', '리뷰어');

SELECT * FROM TBL_CUSTOMER;